import type { Metadata } from "next";
import Loading from "./loading";
import Header from "@/components/header/header";
import Footer from "@/components/footer/footer";
import { CartProvider } from "@/lib/cartContext";

import "bootstrap/dist/css/bootstrap.css";

import "../../public/packages/fontawesome/css/all.min.css";
import "../../public/fonts/stylesheet.css";
import { Fancybox } from "@fancyapps/ui";
import "@fancyapps/ui/dist/fancybox/fancybox.css";
import "../../public/packages/select2.min.css";
import "../../public/packages/meanmenu.min.css";
import "@/styles/main.sass";
import ScriptLoader from "@/components/ScriptLoader";
import { ReactNode } from "react";

export const metadata: Metadata = {
  title: "Helentio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {

  return (
    <html lang="en">
      <ScriptLoader />
      <body>
          <Loading />
          <CartProvider>
          <main>
            <Header />
            
            {children}
            <Footer />
          </main>
          </CartProvider>

         
      </body>
    </html>
  );
}
